### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by orhun** [reemus-dev/gitnr#10]
Is this actively maintained? 👀 If so, can we get a new maintenance release soon?

**Comment by realfresh** [comment]
Hey, sorry, I don't check up on this very often, but it is something I intend to check in on a couple of times a year to review any PRs or do light maintenance. 

Do appreciate your PR, I'll review and create a new release for it this weekend.

Btw, thought I recognised your username, love your work man!

**Comment by orhun** [comment]
Awesome, thanks! Great to hear that ❤️
